'use strict';
(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT'];
const TFS={'15':{label:'15m',ms:900000},'60':{label:'1h',ms:3600000},'240':{label:'4h',ms:14400000}};
const GENESIS='0'.repeat(64);
const KEY='nexus-windows-product-v4';
const POLICY={id:'windows-paper-risk',version:'v1',maxPosition:.20,maxAggregate:.50,maxDailyLoss:.05,maxDrawdown:.10,maxSignals:20,minStop:.002,maxStop:.10,minTarget:.002,maxFee:.01,maxSlippageBps:100,strategies:['momentum','trend_breakout','mean_reversion']};
const MODULES=[
  ['Public Market','read-only Bybit','ok'],['Research Lab','phase6 pipeline + local preview','ok'],['Strategy Factory','3 bounded families','ok'],['Decision / Risk','deterministic final authority','ok'],
  ['Paper Execution','local deterministic simulator','ok'],['AI Room','local + bounded gateway','ok'],['Mission Control','local + gateway projection','ok'],['Audit / Replay','SHA-256 event chain','ok'],['Live Trading','Owner L4 required','locked']
];
const DEFAULT={theme:'dark',sidebarCollapsed:false,view:'dashboard',paper:{openingCash:1000,cash:1000,realized:0,sessionOpen:true,killSwitch:false,signalsToday:0,positions:{},ledger:[],lastRisk:null},ai:[],selectedStrategy:'momentum'};
let state=loadState(), markets=new Map(), appMeta=null, gatewayMeta=null;
function clone(v){return JSON.parse(JSON.stringify(v))}
function merge(a,b){if(!b||typeof b!=='object')return a;for(const[k,v]of Object.entries(b)){if(v&&typeof v==='object'&&!Array.isArray(v)&&a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k]))merge(a[k],v);else a[k]=v}return a}
function loadState(){try{return merge(clone(DEFAULT),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmt(v,d=2){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('fa-IR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(n):'—'}
function compact(v,d=4){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n):'—'}
function px(v){const n=Number(v);return Number.isFinite(n)?compact(n,n>=1000?2:n>=1?4:8):'—'}
function nowIso(){return new Date().toISOString()}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function applyTheme(){document.body.classList.toggle('light',state.theme==='light');$('#theme').textContent=state.theme==='light'?'☾':'☀'}
function applySidebar(){document.body.classList.toggle('sidebar-collapsed',!!state.sidebarCollapsed);const b=$('#sidebarToggle');b.textContent=state.sidebarCollapsed?'▶':'◀';b.setAttribute('aria-expanded',String(!state.sidebarCollapsed))}
function switchView(view){if(!$('#view-'+view))return;state.view=view;save();$$('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===view));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#crumb').textContent='NEXUS / '+({dashboard:'COMMAND CENTER',market:'PUBLIC MARKET',paper:'PAPER EXECUTION',research:'RESEARCH LAB',ai:'AI ROOM',mission:'MISSION CONTROL',audit:'AUDIT / REPLAY',live:'LIVE / LOCKED',settings:'SETTINGS'}[view]||view).toUpperCase();$('.viewport').scrollTo({top:0,left:0})}
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function sha256(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a))}const m=2**32,words=[],text=unescape(encodeURIComponent(ascii)),bit=text.length*8;if(!sha256.h){const h=[],k=[],comp={};for(let c=2,n=0;n<64;c++){if(!comp[c]){for(let i=0;i<313;i+=c)comp[i]=c;h[n]=(Math.sqrt(c)*m)|0;k[n]=(Math.pow(c,1/3)*m)|0;n++}}sha256.h=h;sha256.k=k}let hash=sha256.h.slice(0,8),msg=text+'\x80';while(msg.length%64!==56)msg+='\x00';for(let i=0;i<msg.length;i++)words[i>>2]|=msg.charCodeAt(i)<<((3-i)%4)*8;words.push((bit/m)|0,bit|0);for(let j=0;j<words.length;j+=16){const w=words.slice(j,j+16),old=hash.slice();for(let i=0;i<64;i++){const w15=w[i-15],w2=w[i-2],a=hash[0],e=hash[4],t1=(hash[7]+(rr(e,6)^rr(e,11)^rr(e,25))+((e&hash[5])^((~e)&hash[6]))+sha256.k[i]+(w[i]=i<16?w[i]:(w[i-16]+(rr(w15,7)^rr(w15,18)^(w15>>>3))+w[i-7]+(rr(w2,17)^rr(w2,19)^(w2>>>10)))|0))|0,t2=((rr(a,2)^rr(a,13)^rr(a,22))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2])))|0;hash=[(t1+t2)|0,a,hash[1],hash[2],(hash[3]+t1)|0,e,hash[5],hash[6]]}hash=hash.map((x,i)=>(x+old[i])|0)}return hash.map(x=>('00000000'+(x>>>0).toString(16)).slice(-8)).join('')}
function appendEvent(type,payload,{correlation='desktop-paper',causation='manual'}={}){const ledger=state.paper.ledger,prev=ledger.length?ledger[ledger.length-1].event_digest:GENESIS;const core={schema_version:'nexus.paper-event.desktop.v1',event_id:`desktop:${ledger.length+1}:${type}:${Date.now()}`,event_type:type,aggregate_id:'desktop-demo-account',sequence:ledger.length+1,occurred_at:nowIso(),correlation_id:correlation,causation_id:causation,previous_event_digest:prev,paper_trading_only:true,payload};const event={...core,event_digest:sha256(canonical(core))};ledger.push(event);if(ledger.length>1000)ledger.splice(0,ledger.length-1000);save();return event}
function bootstrapLedger(){if(state.paper.ledger.length)return;appendEvent('demo_account_opened',{currency:'USDT',opening_cash:String(state.paper.openingCash)});appendEvent('session_boundary_recorded',{boundary:'open'});appendSnapshot('bootstrap')}
function appendSnapshot(correlation){appendEvent('equity_snapshot_recorded',{cash:String(state.paper.cash),equity:String(equity()),realized_pnl:String(state.paper.realized),unrealized_pnl:String(unrealized()),open_positions:Object.keys(state.paper.positions)}, {correlation,causation:'projection'})}
function verifyLedger(){let prev=GENESIS;for(let i=0;i<state.paper.ledger.length;i++){const e=state.paper.ledger[i];if(e.sequence!==i+1||e.previous_event_digest!==prev||e.paper_trading_only!==true)return{ok:false,index:i+1,reason:'chain_mismatch'};const{event_digest,...core}=e;if(sha256(canonical(core))!==event_digest)return{ok:false,index:i+1,reason:'digest_mismatch'};prev=e.event_digest}return{ok:true,count:state.paper.ledger.length,last:prev}}
function replayLedger(){let lastSnapshot=null,open=new Set();for(const e of state.paper.ledger){if(e.event_type==='position_opened')open.add(String(e.payload.symbol));if(e.event_type==='position_closed')open.delete(String(e.payload.symbol));if(e.event_type==='equity_snapshot_recorded')lastSnapshot=e.payload}if(!lastSnapshot)return{ok:false,reason:'no_snapshot'};const cashOk=Math.abs(Number(lastSnapshot.cash)-Number(state.paper.cash))<1e-8;const expected=[...open].sort().join(','),actual=Object.keys(state.paper.positions).sort().join(',');return{ok:cashOk&&expected===actual,cashOk,positionsOk:expected===actual,projectedCash:Number(lastSnapshot.cash),open:[...open]}}
function key(symbol,tf){return `${symbol}:${tf}`}
function currentMarket(symbol=$('#symbol')?.value||SYMBOLS[0],tf=$('#timeframe')?.value||'15'){return markets.get(key(symbol,tf))}
function markFor(symbol){const exact=markets.get(key(symbol,$('#timeframe')?.value||'15'));if(exact)return exact.latest.c;for(const[k,v]of markets)if(k.startsWith(symbol+':'))return v.latest.c;return null}
function normalizeMarket(symbol,tf,payload){const p=typeof payload==='string'?JSON.parse(payload):payload;if(!p||p.retCode!==0||!Array.isArray(p.result?.list))throw new Error('invalid market response');const step=TFS[tf].ms,now=Date.now();const candles=p.result.list.slice().reverse().map(r=>({t:Number(r[0]),o:Number(r[1]),h:Number(r[2]),l:Number(r[3]),c:Number(r[4]),v:Number(r[5])})).filter(c=>Number.isFinite(c.t)&&Number.isFinite(c.c)&&c.t+step<=now);if(candles.length<2)throw new Error('insufficient closed candles');const latest=candles[candles.length-1],prev=candles[candles.length-2];return{symbol,tf,candles,latest,change:(latest.c-prev.c)/prev.c*100,received_at:nowIso()}}
async function requestMarket(symbol,tf){if(!window.NexusNative?.requestPublicMarket)throw new Error('native market bridge unavailable');return normalizeMarket(symbol,tf,await window.NexusNative.requestPublicMarket(symbol,tf))}
async function refreshMarket(symbol=$('#symbol').value,tf=$('#timeframe').value,{quiet=false}={}){const chip=$('#marketChip'),msg=$('#marketMessage');if(!quiet){msg.textContent='در حال دریافت...';chip.className='status-chip';chip.querySelector('b').textContent='MARKET CONNECTING'}try{const m=await requestMarket(symbol,tf);markets.set(key(symbol,tf),m);if(!quiet){msg.textContent=`${m.candles.length} closed candles`;chip.className='status-chip ok';chip.querySelector('b').textContent='MARKET ONLINE'}processProtective(symbol,m);renderMarket();renderPaper();renderDashboard();return m}catch(e){if(!quiet){msg.textContent='عدم دسترسی: '+e.message;chip.className='status-chip danger';chip.querySelector('b').textContent='MARKET UNAVAILABLE'}renderMarket();return null}}
async function refreshAllMarket(){const tf=$('#timeframe').value;$('#marketMessage').textContent='به‌روزرسانی همه نمادها...';for(const s of SYMBOLS)await refreshMarket(s,tf,{quiet:true});const any=SYMBOLS.some(s=>markets.has(key(s,tf)));$('#marketChip').className='status-chip '+(any?'ok':'danger');$('#marketChip').querySelector('b').textContent=any?'MARKET ONLINE':'MARKET UNAVAILABLE';$('#marketMessage').textContent=any?'به‌روزرسانی کامل شد':'داده‌ای دریافت نشد';renderMarket();renderPaper();renderDashboard()}
function chartSvg(candles){const vals=candles.slice(-80).map(c=>c.c),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,w=900,h=180,pad=8;const pts=vals.map((v,i)=>`${pad+i*(w-2*pad)/Math.max(1,vals.length-1)},${pad+(max-v)*(h-2*pad)/span}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="price series"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="1.6" vector-effect="non-scaling-stroke"/></svg>`}
function renderMarket(){const s=$('#symbol').value,tf=$('#timeframe').value,m=markets.get(key(s,tf));$('#quoteSymbol').textContent=s;if(!m){$('#quotePrice').textContent='—';$('#quoteChange').textContent='—';$('#quoteOpen').textContent=$('#quoteHigh').textContent=$('#quoteLow').textContent=$('#quoteVolume').textContent='—';$('#quoteTime').textContent='—';$('#marketChart').innerHTML='<div class="chart-empty">NO CLOSED CANDLE DATA</div>';$('#candleRows').innerHTML='<tr><td colspan="6" class="muted">داده دریافت نشده است.</td></tr>'}else{const c=m.latest;$('#quotePrice').textContent=px(c.c);$('#quoteChange').textContent=(m.change>=0?'+':'')+m.change.toFixed(3)+'%';$('#quoteChange').className='quote-change '+(m.change>=0?'good':'bad');$('#quoteOpen').textContent=px(c.o);$('#quoteHigh').textContent=px(c.h);$('#quoteLow').textContent=px(c.l);$('#quoteVolume').textContent=compact(c.v,2);$('#quoteTime').textContent=new Date(c.t).toLocaleString('fa-IR');$('#marketChart').innerHTML=chartSvg(m.candles);$('#candleRows').innerHTML=m.candles.slice(-20).reverse().map(x=>`<tr><td>${new Date(x.t).toLocaleString('fa-IR')}</td><td class="num">${px(x.o)}</td><td class="num">${px(x.h)}</td><td class="num">${px(x.l)}</td><td class="num">${px(x.c)}</td><td class="num">${compact(x.v,2)}</td></tr>`).join('')}
  $('#watchMarket').innerHTML=SYMBOLS.map(sym=>{const x=markets.get(key(sym,tf));return `<div class="watch-row" data-watch-symbol="${sym}"><b>${sym}</b><span>${x?px(x.latest.c):'—'}</span><span class="${x?(x.change>=0?'good':'bad'):'muted'}">${x?((x.change>=0?'+':'')+x.change.toFixed(2)+'%'):'—'}</span></div>`}).join('');$$('[data-watch-symbol]').forEach(r=>r.onclick=()=>{$('#symbol').value=r.dataset.watchSymbol;renderMarket()})}
function exposure(){return Object.values(state.paper.positions).reduce((n,p)=>n+Number(p.qty)*Number(p.entry),0)}
function unrealized(){return Object.values(state.paper.positions).reduce((n,p)=>{const m=markFor(p.symbol)??Number(p.entry);return n+(p.side==='long'?(m-p.entry):(p.entry-m))*p.qty},0)}
function equity(){return Number(state.paper.cash)+unrealized()}
function risk(ticket){const p=state.paper,eq=equity(),proposed=ticket.qty*ticket.price,current=exposure();let reason='risk_allowed';if(p.killSwitch)reason='kill_switch_enabled';else if(!p.sessionOpen)reason='session_closed';else if(!SYMBOLS.includes(ticket.symbol))reason='symbol_unsupported';else if(!TFS[ticket.tf])reason='timeframe_unsupported';else if(!POLICY.strategies.includes(ticket.strategy))reason='strategy_ineligible';else if(!['long','short'].includes(ticket.side))reason='side_unsupported';else if(!(ticket.qty>0&&ticket.price>0))reason='invalid_size_or_price';else if(p.positions[ticket.symbol])reason='position_exists';else if(!(ticket.fee>=0&&ticket.fee<=POLICY.maxFee))reason='fee_rate_out_of_bounds';else if(!(ticket.slip>=0&&ticket.slip<=POLICY.maxSlippageBps))reason='slippage_out_of_bounds';else if(p.signalsToday>=POLICY.maxSignals)reason='session_signal_limit';else if(p.realized<-(p.openingCash*POLICY.maxDailyLoss))reason='daily_loss_limit';else if((p.openingCash-eq)/p.openingCash>POLICY.maxDrawdown)reason='drawdown_limit';else if(proposed>eq*POLICY.maxPosition)reason='position_size_limit';else if(current+proposed>eq*POLICY.maxAggregate)reason='aggregate_exposure_limit';else{const sd=Math.abs(ticket.price-ticket.stop)/ticket.price,td=Math.abs(ticket.target-ticket.price)/ticket.price;if(sd<POLICY.minStop||sd>POLICY.maxStop)reason='stop_distance_invalid';else if(td<POLICY.minTarget)reason='target_distance_invalid';else if(ticket.side==='long'&&!(ticket.stop<ticket.price&&ticket.price<ticket.target))reason='protective_prices_invalid';else if(ticket.side==='short'&&!(ticket.target<ticket.price&&ticket.price<ticket.stop))reason='protective_prices_invalid'}return{allowed:reason==='risk_allowed',reason_code:reason,policy_id:POLICY.id,policy_version:POLICY.version,proposed_notional:proposed,resulting_exposure:current+proposed,equity:eq}}
function readTicket(){return{symbol:$('#paperSymbol').value,tf:$('#timeframe').value,side:$('#paperSide').value,strategy:$('#paperStrategy').value,qty:Number($('#paperQty').value),price:Number($('#paperPrice').value),stop:Number($('#paperStop').value),target:Number($('#paperTarget').value),fee:Number($('#paperFee').value)/100,slip:Number($('#paperSlip').value)}}
function protectiveDefaults(){const p=Number($('#paperPrice').value),side=$('#paperSide').value;if(!(p>0))return;$('#paperStop').value=(side==='long'?p*.985:p*1.015).toFixed(p>=1000?2:6);$('#paperTarget').value=(side==='long'?p*1.03:p*.97).toFixed(p>=1000?2:6)}
function previewRisk(){const d=risk(readTicket());state.paper.lastRisk={...d,evaluated_at:nowIso(),source:'desktop-deterministic-mirror'};save();renderRisk();return d}
function renderRisk(){const d=state.paper.lastRisk,b=$('#riskBanner');if(!d){b.className='risk-banner';b.querySelector('strong').textContent='RISK: NOT EVALUATED';b.querySelector('span').textContent='—';return}b.className='risk-banner '+(d.allowed?'allow':'deny');b.querySelector('strong').textContent=d.allowed?'RISK: ALLOW':'RISK: DENY';b.querySelector('small').textContent=d.reason_code;b.querySelector('span').textContent=compact(d.proposed_notional,2)+' USDT'}
function executePaper(){const t=readTicket(),d=previewRisk();if(!d.allowed){toast('Risk رد کرد: '+d.reason_code);return}const dir=t.side==='long'?1:-1,fill=t.price*(1+dir*t.slip/10000),fee=fill*t.qty*t.fee,slipCost=Math.abs(fill-t.price)*t.qty,c=`paper-open-${Date.now()}`;state.paper.cash-=fee+slipCost;state.paper.positions[t.symbol]={symbol:t.symbol,side:t.side,strategy:t.strategy,qty:t.qty,entry:fill,stop:t.stop,target:t.target,opened_at:nowIso(),fee_rate:t.fee,slippage_bps:t.slip};state.paper.signalsToday++;appendEvent('order_intent_recorded',{symbol:t.symbol,side:t.side,quantity:String(t.qty),order_type:'paper_open'},{correlation:c,causation:c});appendEvent('risk_decision_recorded',{decision:'allow',reason_code:d.reason_code,policy_id:d.policy_id},{correlation:c,causation:c});appendEvent('simulated_fill_recorded',{symbol:t.symbol,side:t.side,quantity:String(t.qty),price:String(fill)},{correlation:c,causation:c});appendEvent('position_opened',{symbol:t.symbol,side:t.side,strategy:t.strategy,quantity:String(t.qty),entry_price:String(fill),stop:String(t.stop),target:String(t.target)},{correlation:c,causation:c});appendEvent('fee_recorded',{amount:String(fee),currency:'USDT'},{correlation:c,causation:c});appendEvent('slippage_recorded',{amount:String(slipCost),currency:'USDT'},{correlation:c,causation:c});appendSnapshot(c);save();renderAll();toast('Paper position opened')}
function closePosition(symbol,ref=null,reason='manual_close'){const p=state.paper.positions[symbol];if(!p)return;if(state.paper.killSwitch&&reason==='manual_close'){state.paper.lastRisk={allowed:false,reason_code:'kill_switch_enabled',evaluated_at:nowIso(),source:'desktop-deterministic-mirror'};renderRisk();toast('Kill Switch close دستی را متوقف کرده');return}const mark=Number(ref??markFor(symbol)??p.entry),dir=p.side==='long'?-1:1,fill=mark*(1+dir*p.slippage_bps/10000),gross=(p.side==='long'?fill-p.entry:p.entry-fill)*p.qty,fee=fill*p.qty*p.fee_rate,slipCost=Math.abs(fill-mark)*p.qty,net=gross-fee-slipCost,c=`paper-close-${Date.now()}`;state.paper.cash+=net;state.paper.realized+=net;delete state.paper.positions[symbol];state.paper.lastRisk={allowed:true,reason_code:'risk_allowed_exit',evaluated_at:nowIso(),source:'desktop-deterministic-mirror'};appendEvent('order_intent_recorded',{symbol,side:p.side,quantity:String(p.qty),order_type:'paper_close',reason},{correlation:c,causation:c});appendEvent('risk_decision_recorded',{decision:'allow',reason_code:'risk_allowed_exit'},{correlation:c,causation:c});appendEvent('simulated_fill_recorded',{symbol,quantity:String(p.qty),price:String(fill)},{correlation:c,causation:c});appendEvent('position_closed',{symbol,exit_price:String(fill),realized_pnl:String(net),reason},{correlation:c,causation:c});appendEvent('fee_recorded',{amount:String(fee),currency:'USDT'},{correlation:c,causation:c});appendEvent('slippage_recorded',{amount:String(slipCost),currency:'USDT'},{correlation:c,causation:c});appendSnapshot(c);save();renderAll();toast(`${symbol} paper position closed`)}
function processProtective(symbol,m){const p=state.paper.positions[symbol];if(!p||!m?.latest)return;const c=m.latest;let hit=null,ref=null;if(p.side==='long'){if(c.l<=p.stop){hit='protective_stop';ref=p.stop}else if(c.h>=p.target){hit='protective_target';ref=p.target}}else{if(c.h>=p.stop){hit='protective_stop';ref=p.stop}else if(c.l<=p.target){hit='protective_target';ref=p.target}}if(hit)closePosition(symbol,ref,hit)}
function fillFromMarket(){const sym=$('#paperSymbol').value,m=markets.get(key(sym,$('#timeframe').value));if(!m){toast('ابتدا داده بازار این نماد را دریافت کن');return}$('#paperPrice').value=m.latest.c;protectiveDefaults();previewRisk()}
function resetPaper(){if(Object.keys(state.paper.positions).length){toast('قبل از Reset پوزیشن‌های Paper را ببند');return}state.paper=clone(DEFAULT.paper);bootstrapLedger();save();renderAll();toast('Demo account reset')}
function renderPaper(){const p=state.paper,u=unrealized(),eq=equity();$('#paperCash').textContent=fmt(p.cash);$('#paperEquity').textContent=fmt(eq);$('#paperUnrealized').textContent=fmt(u);$('#paperRealized').textContent=fmt(p.realized);$('#dashEquity').textContent=fmt(eq);$('#dashPositions').textContent=Object.keys(p.positions).length;$('#dashRealized').textContent=fmt(p.realized);$('#dashRealized').className=p.realized>0?'good':p.realized<0?'bad':'';$('#dashRisk').textContent=p.killSwitch?'KILL':p.sessionOpen?'READY':'SESSION CLOSED';$('#dashRisk').className=p.killSwitch?'bad':p.sessionOpen?'good':'warn';$('#positionCount').textContent=`${Object.keys(p.positions).length} POSITIONS`;$('#sessionToggle').textContent=p.sessionOpen?'بستن Session':'باز کردن Session';$('#killToggle').textContent=p.killSwitch?'خاموش‌کردن Kill Switch':'فعال‌کردن Kill Switch';$('#killToggle').className='btn '+(p.killSwitch?'warn':'danger');$('#paperPolicy').textContent=`Policy ${POLICY.version} · max position ${(POLICY.maxPosition*100).toFixed(0)}% equity · aggregate ${(POLICY.maxAggregate*100).toFixed(0)}% · daily loss ${(POLICY.maxDailyLoss*100).toFixed(0)}% · drawdown ${(POLICY.maxDrawdown*100).toFixed(0)}% · signals/day ${POLICY.maxSignals}`;const rows=Object.values(p.positions).map(x=>{const m=markFor(x.symbol)??x.entry,pnl=(x.side==='long'?m-x.entry:x.entry-m)*x.qty;return `<tr><td class="num">${x.symbol}</td><td>${x.side.toUpperCase()}</td><td>${x.strategy}</td><td class="num">${compact(x.qty,8)}</td><td class="num">${px(x.entry)}</td><td class="num">${px(m)}</td><td class="num ${pnl>=0?'good':'bad'}">${compact(pnl,4)}</td><td class="num">${px(x.stop)}</td><td class="num">${px(x.target)}</td><td><button class="btn" data-close-position="${x.symbol}">Close</button></td></tr>`}).join('');$('#positionRows').innerHTML=rows||'<tr><td colspan="10" class="muted">پوزیشن Paper باز وجود ندارد.</td></tr>';$$('[data-close-position]').forEach(b=>b.onclick=()=>closePosition(b.dataset.closePosition));renderRisk()}
function strategySignal(strategy,c,i){if(i<30)return 0;if(strategy==='momentum'){const sma=(n,end)=>c.slice(end-n+1,end+1).reduce((s,x)=>s+x.c,0)/n,fast=sma(10,i),slow=sma(30,i),pf=sma(10,i-1),ps=sma(30,i-1);if(fast>slow&&pf<=ps)return 1;if(fast<slow&&pf>=ps)return-1;return 0}if(strategy==='trend_breakout'){const prev=c.slice(i-20,i),hi=Math.max(...prev.map(x=>x.h)),lo=Math.min(...prev.map(x=>x.l));if(c[i].c>hi)return 1;if(c[i].c<lo)return-1;return 0}const win=c.slice(i-19,i+1).map(x=>x.c),mean=win.reduce((a,b)=>a+b,0)/win.length,sd=Math.sqrt(win.reduce((s,x)=>s+(x-mean)**2,0)/win.length)||1,z=(c[i].c-mean)/sd;return z<-1.5?1:z>1.5?-1:0}
function runResearch(){const sym=$('#researchSymbol').value,tf=$('#researchTf').value,m=markets.get(key(sym,tf));if(!m){$('#researchNotes').textContent='داده این Symbol/Timeframe در حافظه نیست؛ ابتدا از بخش بازار دریافتش کن.';toast('Market data required');return}const c=m.candles,strategy=state.selectedStrategy,rets=[];for(let i=30;i<c.length-8;i++){const sig=strategySignal(strategy,c,i);if(!sig)continue;const entry=c[i+1].o,exit=c[i+7].o;if(entry>0&&exit>0)rets.push(sig*(exit-entry)/entry)}let equityCurve=1,peak=1,maxDd=0,wins=0;for(const r of rets){equityCurve*=1+r;if(r>0)wins++;peak=Math.max(peak,equityCurve);maxDd=Math.max(maxDd,(peak-equityCurve)/peak)}const total=(equityCurve-1)*100,win=rets.length?wins/rets.length*100:0;$('#rTrades').textContent=rets.length;$('#rWin').textContent=win.toFixed(1)+'%';$('#rReturn').textContent=(total>=0?'+':'')+total.toFixed(2)+'%';$('#rReturn').className=total>0?'good':total<0?'bad':'';$('#rDd').textContent=(maxDd*100).toFixed(2)+'%';$('#rStatus').textContent=rets.length?'PREVIEW ONLY':'NO SIGNALS';$('#researchNotes').textContent=`${strategy} · ${sym} · ${TFS[tf].label} · entry روی open کندل بعدی و خروج افق ثابت 6 کندل. این preview محلی، qualification رسمی Strategy Factory یا ادعای سود نیست.`;appendEvent('research_preview_recorded',{strategy,symbol:sym,timeframe:tf,trades:rets.length,return_pct:total,max_drawdown_pct:maxDd*100},{correlation:`research-${Date.now()}`,causation:'local-preview'});renderAudit();renderDashboard()}
function aiAdd(role,text,source='local'){state.ai.push({role,text:String(text).slice(0,12000),source,at:nowIso()});if(state.ai.length>100)state.ai.splice(0,state.ai.length-100);save();renderAi()}
function localAiReply(message){const m=message.toLowerCase(),p=state.paper,eq=equity(),positions=Object.keys(p.positions).length;if(m.includes('ریسک')||m.includes('risk'))return `Risk authority قطعی است. وضعیت فعلی: equity=${fmt(eq)} USDT، positions=${positions}، session=${p.sessionOpen?'open':'closed'}، killSwitch=${p.killSwitch?'on':'off'}. من می‌توانم تحلیل/پیشنهاد بدهم اما Risk Gate را دور نمی‌زنم.`;if(m.includes('استراتژی')||m.includes('strategy'))return `سه خانواده ثبت‌شده: momentum، trend_breakout و mean_reversion. برای evidence محلی از Research Preview استفاده کن؛ qualification رسمی نیازمند OOS/Stress/Regime pipeline است.`;if(m.includes('پوزیشن')||m.includes('trade')||m.includes('معامله'))return `Paper فقط: ${positions} پوزیشن باز و realized=${fmt(p.realized)} USDT. برای stage کردن پیشنهاد، دکمه Paper-stage را بزن؛ اجرا همچنان نیازمند Risk Gate است.`;return `NEXUS Ops Room: پیام دریافت شد. Market، Research، Paper، Risk، Mission و Audit در این desktop یکپارچه‌اند. Live authority قفل است؛ اقدام من در این build به تحلیل، پیشنهاد و Paper-stage محدود می‌ماند.`}
function pickAiText(p){if(typeof p==='string')return p;if(!p||typeof p!=='object')return JSON.stringify(p);for(const k of['answer','response','message','content','summary','text'])if(typeof p[k]==='string')return p[k];for(const k of['data','payload','result']){const x=pickAiText(p[k]);if(x&&x!=='undefined')return x}return JSON.stringify(p,null,2)}
async function sendAi(){const box=$('#aiMessage'),message=box.value.trim();if(!message)return;box.value='';aiAdd('user',message,'user');const mode=$('#aiMode').value;if(mode==='local'){aiAdd('ai',localAiReply(message),'local deterministic');return}const payload={session_id:'desktop',conversation_id:'nexus-windows-v4',turn_id:`turn-${Date.now()}`,message};try{if(!window.NexusNative?.requestAiRoom)throw new Error('AI gateway bridge unavailable');const raw=await window.NexusNative.requestAiRoom(JSON.stringify(payload)),parsed=typeof raw==='string'?JSON.parse(raw):raw;aiAdd('ai',pickAiText(parsed),'secure gateway')}catch(e){if(mode==='gateway')aiAdd('ai','Gateway AI Room unavailable: '+e.message,'gateway error');else aiAdd('ai',localAiReply(message)+'\n\n[Gateway unavailable; local bounded fallback used.]','local fallback')}}
function renderAi(){const log=$('#chatLog');log.innerHTML='';const messages=state.ai.length?state.ai:[{role:'ai',text:'NEXUS AI Room آماده است. سطح عملیاتی این build: تحلیل، پیشنهاد و Paper-stage؛ Live قفل است.',source:'system',at:nowIso()}];for(const m of messages){const d=document.createElement('div');d.className='message '+(m.role==='user'?'user':'ai');const meta=document.createElement('div');meta.className='meta';meta.textContent=`${m.role==='user'?'USER':'NEXUS'} · ${m.source} · ${new Date(m.at).toLocaleTimeString('fa-IR')}`;const p=document.createElement('p');p.textContent=m.text;d.append(meta,p);log.appendChild(d)}log.scrollTop=log.scrollHeight}
function stageAiPaper(){const m=currentMarket();if(!m){toast('ابتدا Market data دریافت کن');return}$('#paperSymbol').value=m.symbol;$('#paperPrice').value=m.latest.c;$('#paperStrategy').value=state.selectedStrategy;protectiveDefaults();previewRisk();aiAdd('ai',`Paper-stage آماده شد: ${m.symbol} با strategy=${state.selectedStrategy}. هیچ سفارش واقعی ارسال نشده؛ قبل از اجرای Paper، Risk Gate را بررسی کن.`,'paper-stage');switchView('paper')}
function renderMission(){const defs=[['Market Feed',markets.size?'ONLINE':'IDLE',markets.size?'closed candles cached':'waiting for request'],['Research Engine','READY','local preview + Phase 6 backend contract'],['Deterministic Risk',state.paper.killSwitch?'HALTED':'READY','final authority'],['Paper Executor',state.paper.sessionOpen?'READY':'SESSION CLOSED',`${Object.keys(state.paper.positions).length} open positions`],['AI Room','BOUNDED','local + optional secure gateway'],['Audit Chain',verifyLedger().ok?'VERIFIED':'FAULT',`${state.paper.ledger.length} events`],['Mission Control','READY','local projection'],['Live Executor','LOCKED','Owner L4 / no endpoint']];$('#missionGrid').innerHTML=defs.map(([n,s,d])=>`<article class="agent"><div class="agent-head"><b>${n}</b><span class="${s==='LOCKED'||s==='HALTED'?'warn':''}">${s}</span></div><p>${d}</p></article>`).join('')}
async function syncMission(){const out=$('#missionRemote');out.textContent='Syncing...';try{if(!window.NexusNative?.request)throw new Error('gateway bridge unavailable');const raw=await window.NexusNative.request(JSON.stringify({path:'/api/mission-control'})),p=typeof raw==='string'?JSON.parse(raw):raw;out.textContent=JSON.stringify(p,null,2).slice(0,30000);$('#gatewayChip').className='status-chip ok';$('#gatewayChip').querySelector('b').textContent='GATEWAY ONLINE';toast('Mission Control synced')}catch(e){out.textContent='Gateway mission projection unavailable: '+e.message;$('#gatewayChip').className='status-chip warn';$('#gatewayChip').querySelector('b').textContent='GATEWAY LOCAL';}}
function renderAudit(){const v=verifyLedger(),r=replayLedger(),last=state.paper.ledger.at(-1);$('#auditCount').textContent=state.paper.ledger.length;$('#auditStatus').textContent=v.ok?'VERIFIED':'FAULT';$('#auditStatus').className=v.ok?'good':'bad';$('#replayStatus').textContent=r.ok?'MATCH':'CHECK';$('#replayStatus').className=r.ok?'good':'warn';$('#digestShort').textContent=last?last.event_digest.slice(0,12)+'…':'—';$('#auditDigest').textContent=last?last.event_digest:'—';$('#auditRows').innerHTML=state.paper.ledger.slice(-80).reverse().map(e=>`<tr><td class="num">${e.sequence}</td><td>${new Date(e.occurred_at).toLocaleString('fa-IR')}</td><td>${e.event_type}</td><td class="num">${e.correlation_id}</td><td class="num">${e.event_digest.slice(0,16)}…</td></tr>`).join('')||'<tr><td colspan="5">No events</td></tr>'}
function verifyAudit(){const v=verifyLedger();renderAudit();toast(v.ok?`Audit verified: ${v.count} events`:`Audit fault at ${v.index}: ${v.reason}`)}
function replayAudit(){const r=replayLedger();renderAudit();toast(r.ok?'Replay projection matches current Paper state':'Replay projection mismatch')}
function renderDashboard(){const list=$('#moduleList');list.innerHTML=MODULES.map(([name,detail,status])=>`<div class="module ${status==='locked'?'locked':''}"><i></i><b>${name}</b><small>${detail}</small></div>`).join('');const recent=state.paper.ledger.slice(-6).reverse();$('#activityList').innerHTML=recent.length?recent.map(e=>`<div class="activity-row"><time>${new Date(e.occurred_at).toLocaleTimeString('fa-IR')}</time><span>${e.event_type}</span><b>${e.sequence}</b></div>`).join(''):'<div class="muted">No activity</div>'}
function renderAll(){renderPaper();renderMarket();renderAi();renderMission();renderAudit();renderDashboard()}
async function loadAppMeta(){try{appMeta=await window.NexusNative?.appInfo?.();if(appMeta){$('#sideVersion').textContent=appMeta.version;$('#appInfo').textContent=`${appMeta.name} ${appMeta.version} · ${appMeta.platform}/${appMeta.arch} · packaged=${appMeta.packaged} · authority=${appMeta.authority}`}}catch(e){$('#appInfo').textContent='App info unavailable: '+e.message}try{gatewayMeta=await window.NexusNative?.gatewayInfo?.();const has=window.NexusNative?.hasKey?.('gateway');$('#gatewayOrigin').textContent=gatewayMeta?.origin||'—';$('#gatewayInfo').textContent=`mode=${gatewayMeta?.mode||'unknown'} · origin=${gatewayMeta?.origin||'—'} · readOnly=${gatewayMeta?.readOnly??true} · boundedAiRoom=${gatewayMeta?.boundedAiRoom??false} · tokenStored=${!!has} · liveTradingAuthority=false`;$('#gatewayChip').querySelector('b').textContent=has?'GATEWAY CONFIGURED':'GATEWAY LOCAL'}catch(e){$('#gatewayInfo').textContent='Gateway info unavailable: '+e.message}}
async function testGateway(){try{const raw=await window.NexusNative.request(JSON.stringify({path:'/health'}));JSON.parse(raw);$('#gatewayChip').className='status-chip ok';$('#gatewayChip').querySelector('b').textContent='GATEWAY ONLINE';toast('Gateway connection OK')}catch(e){$('#gatewayChip').className='status-chip warn';$('#gatewayChip').querySelector('b').textContent='GATEWAY UNAVAILABLE';toast('Gateway unavailable: '+e.message)}}
function setupControls(){const opts=SYMBOLS.map(s=>`<option value="${s}">${s}</option>`).join('');$('#symbol').innerHTML=opts;$('#paperSymbol').innerHTML=opts;$('#researchSymbol').innerHTML=opts;const tf=Object.entries(TFS).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');$('#timeframe').innerHTML=tf;$('#researchTf').innerHTML=tf;$('#paperSymbol').value='BTCUSDT';$('#researchSymbol').value='BTCUSDT';$('#researchTf').value='15'}
function bind(){$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#sidebarToggle').onclick=()=>{state.sidebarCollapsed=!state.sidebarCollapsed;save();applySidebar()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='b'){e.preventDefault();state.sidebarCollapsed=!state.sidebarCollapsed;save();applySidebar()}});$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()};$('#refreshMarket').onclick=()=>refreshMarket();$('#loadAllMarket').onclick=refreshAllMarket;$('#symbol').onchange=renderMarket;$('#timeframe').onchange=()=>{renderMarket();renderPaper()};$('#paperSide').onchange=protectiveDefaults;$('#paperPrice').onchange=protectiveDefaults;$('#fillPaperFromMarket').onclick=fillFromMarket;$('#previewRisk').onclick=previewRisk;$('#executePaper').onclick=executePaper;$('#sessionToggle').onclick=()=>{state.paper.sessionOpen=!state.paper.sessionOpen;appendEvent('session_boundary_recorded',{boundary:state.paper.sessionOpen?'open':'close'});appendSnapshot('session');save();renderAll()};$('#killToggle').onclick=()=>{state.paper.killSwitch=!state.paper.killSwitch;appendEvent('kill_switch_recorded',{enabled:state.paper.killSwitch});save();renderAll()};$('#resetPaper').onclick=resetPaper;$$('[data-strategy]').forEach(b=>b.onclick=()=>{state.selectedStrategy=b.dataset.strategy;save();$$('[data-strategy]').forEach(x=>x.classList.toggle('active',x===b))});$('#runResearch').onclick=runResearch;$('#sendAi').onclick=sendAi;$('#aiMessage').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.ctrlKey){e.preventDefault();sendAi()}});$('#aiPaperStage').onclick=stageAiPaper;$('#syncMission').onclick=syncMission;$('#verifyAudit').onclick=verifyAudit;$('#replayAudit').onclick=replayAudit;$('#saveGateway').onclick=()=>{const v=$('#gatewayToken').value.trim();if(!v){toast('Token خالی است');return}const ok=window.NexusNative?.saveKey?.('gateway',v);$('#gatewayToken').value='';toast(ok?'Gateway token securely stored':'Secure storage failed');loadAppMeta()};$('#deleteGateway').onclick=()=>{const ok=window.NexusNative?.deleteKey?.('gateway');$('#gatewayToken').value='';toast(ok?'Gateway token deleted':'Delete failed');loadAppMeta()};$('#testGateway').onclick=testGateway}
async function init(){setupControls();bootstrapLedger();applyTheme();applySidebar();bind();switchView(state.view||'dashboard');$$('[data-strategy]').forEach(b=>b.classList.toggle('active',b.dataset.strategy===state.selectedStrategy));renderAll();await loadAppMeta();refreshMarket('BTCUSDT','15')}
window.addEventListener('DOMContentLoaded',init);
})();
