(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={overview:null,paper:null,events:null,strategies:null,mission:null,lastRisk:null,sessionId:'nexus-ui-'+crypto.randomUUID(),conversationId:'product-'+crypto.randomUUID(),turn:0};
const labels={overview:['NEXUS / MISSION CONTROL','مرکز فرمان NEXUS'],paper:['NEXUS / PAPER EXECUTION','ترید دمو و Paper Execution'],ai:['NEXUS / AI ROOM','اتاق هوش مصنوعی'],strategies:['NEXUS / STRATEGY LAB','Strategy Factory'],research:['NEXUS / RESEARCH LAB','آزمایشگاه پژوهش'],risk:['NEXUS / DECISION / RISK','تصمیم و ریسک'],agents:['NEXUS / AGENTS / QUEUE','عامل‌ها و صف'],audit:['NEXUS / AUDIT / REPLAY','رویداد و بازپخش'],live:['NEXUS / LIVE / LOCKED','ترید اصلی — قفل‌شده']};
function esc(v){return String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}
async function api(path,options={}){const res=await fetch(path,{cache:'no-store',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options});let payload;try{payload=await res.json()}catch{throw Error('پاسخ gateway قابل خواندن نیست')}if(!res.ok)throw Error(payload.detail||payload.error||`HTTP ${res.status}`);return payload}
function setGateway(ok,msg){const p=$('#gatewayState');p.className='status '+(ok?'good':'bad');p.querySelector('b').textContent=msg}
function metric(label,value,detail=''){return`<div class="metric"><span>${esc(label)}</span><b>${esc(value)}</b><small>${esc(detail)}</small></div>`}
function show(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+view).classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageCode').textContent=labels[view][0];$('#pageTitle').textContent=labels[view][1]}
function bool(v){return v===true?'YES':v===false?'NO':'—'}
function statusClass(v){return /available|active|complete|ready|pass|paper/i.test(String(v))?'good':/locked|unavailable|denied|failed|error/i.test(String(v))?'bad':'neutral'}
function renderOverview(){const x=state.overview;if(!x)return;$('#productState').textContent=x.delivery||'product-integration';$('#paperState').textContent=x.paper?.active?'ACTIVE':'UNAVAILABLE';$('#liveState').textContent=(x.live?.status||'LOCKED').toUpperCase();const m=x.mission_control||{};$('#missionBadge').className='badge '+statusClass(m.status);$('#missionBadge').textContent=String(m.status||'unavailable').toUpperCase();const mission=m.mission||{},queue=m.queue||{},counts=queue.counts||{};$('#missionSummary').innerHTML=[metric('MISSION',mission.status||m.status||'unavailable',mission.mission_id||''),metric('READY',counts.ready??counts.READY??'—','queue'),metric('RUNNING',counts.running??counts.RUNNING??'—','queue'),metric('AGENTS',Array.isArray(m.agents)?m.agents.length:'—','registered')].join('');const caps=x.capabilities||{};$('#capabilityMap').innerHTML=Object.entries(caps).map(([k,v])=>`<div class="capability"><span>${esc(k.replaceAll('_',' ').toUpperCase())}</span><b class="${statusClass(v)}">${esc(v)}</b></div>`).join('')}
function renderPaper(){const p=state.paper;if(!p)return;const a=p.account||{};$('#paperMetrics').innerHTML=[metric('CASH',a.cash||'—',a.currency||'USDT'),metric('EQUITY',a.equity||'—','paper'),metric('REALIZED PNL',a.realized_pnl||'0','paper'),metric('EVENTS',p.event_count??'—','hash chained')].join('');const pos=a.positions||[];$('#positions').innerHTML=pos.length?`<table class="data-table"><thead><tr><th>نماد</th><th>جهت</th><th>مقدار</th><th>ورود</th><th>Stop</th><th>Target</th></tr></thead><tbody>${pos.map(r=>{const st=(a.stops||[]).find(x=>x.symbol===r.symbol),tg=(a.targets||[]).find(x=>x.symbol===r.symbol);return`<tr><td class="mono">${esc(r.symbol)}</td><td>${esc(r.side)}</td><td>${esc(r.quantity)}</td><td>${esc(r.entry_price)}</td><td>${esc(st?.price)}</td><td>${esc(tg?.price)}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty-state">پوزیشن بازی وجود ندارد.</div>'}
function renderEvents(){const events=state.events?.events||[];const html=events.slice().reverse().map(e=>`<div class="event-row"><code>#${esc(e.sequence)}</code><b>${esc(e.event_type)}</b><span>${esc(e.payload?.symbol||e.payload?.reason_code||e.payload?.currency||'')}</span><code>${esc((e.event_digest||'').slice(0,16))}…</code></div>`).join('')||'<div class="empty-state">رویدادی وجود ندارد.</div>';$('#paperEvents').innerHTML=html;$('#auditEvents').innerHTML=html;$('#auditDigest').textContent=(state.paper?.head_event_digest||'—').slice(0,20)+'…'}
function renderStrategies(){const s=state.strategies;if(!s)return;$('#strategyFamilies').innerHTML=(s.families||[]).map(x=>`<article class="strategy-card"><span>${esc(x.status)}</span><h3>${esc(x.id)}</h3><p>Promotion ceiling: ${esc(x.promotion_ceiling)} · Live: ${esc(bool(x.live_execution_allowed))}</p></article>`).join('');$('#qualificationPath').innerHTML=(s.qualification_path||[]).map(x=>`<div class="stage">${esc(x)}</div>`).join('')}
function renderMission(){const m=state.mission;if(!m||m.status==='unavailable'){$('#agentState').innerHTML=`<div class="empty-state">Mission Control runtime در این دستگاه هنوز report فعال ندارد. Backend آن در پروژه موجود است اما وضعیت runtime ساختگی نمایش داده نمی‌شود.<br><small>${esc(m?.reason||'')}</small></div>`;return}const q=m.queue||{},agents=m.agents||[],providers=m.providers||{};$('#agentState').innerHTML=`<div class="metric-grid">${metric('MISSION',m.mission?.status||'unknown',m.mission?.mission_id||'')}${metric('QUEUE',JSON.stringify(q.counts||{}),'current projection')}${metric('AGENTS',Array.isArray(agents)?agents.length:'—','registered')}${metric('PROVIDERS',typeof providers==='object'?Object.keys(providers).length:'—','projection')}</div><pre class="json-view">${esc(JSON.stringify({agents,providers,runners:m.runners,local_node:m.local_node,notifications:m.notifications},null,2))}</pre>`}
function renderLive(){const x=state.overview?.live||{};$('#liveDetails').innerHTML=[['STATUS',x.status||'locked'],['AUTHORITY',bool(x.live_trading_authority)],['CREDENTIALS',bool(x.exchange_credentials_configured)],['ORDERS',bool(x.orders_allowed)],['WITHDRAWALS',bool(x.withdrawals_allowed)],['PRODUCTION',bool(x.production_promotion_allowed)]].map(([a,b])=>`<div class="lock-item"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}
async function loadResearch(){try{const r=await api('/api/integrations/research');$('#researchStatus').innerHTML=`<pre class="json-view">${esc(JSON.stringify(r.summary||r,null,2))}</pre>`}catch(e){$('#researchStatus').textContent='Research integration runtime در این دستگاه در دسترس نیست: '+e.message}}
async function loadAll(){setGateway(false,'در حال اتصال');try{const [overview,paper,events,strategies,mission]=await Promise.all([api('/api/product/overview'),api('/api/product/paper'),api('/api/product/paper/events?limit=100'),api('/api/product/strategies'),api('/api/product/mission-control')]);Object.assign(state,{overview,paper,events,strategies,mission});renderOverview();renderPaper();renderEvents();renderStrategies();renderMission();renderLive();setGateway(true,'محصول متصل');loadResearch()}catch(e){setGateway(false,'Gateway unavailable');toast(e.message)}}
async function submitPaper(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={};for(const [k,v] of f.entries())payload[k]=String(v).trim();const out=$('#orderResult');out.className='result-box muted';out.textContent='در حال ارزیابی Risk…';try{const r=await api('/api/product/paper/order',{method:'POST',body:JSON.stringify(payload)});state.lastRisk=r;$('#lastRisk').textContent=JSON.stringify(r,null,2);out.className='result-box '+(r.accepted?'good':'bad');out.textContent=r.accepted?`ACCEPTED\nFill: ${r.execution.fill_price}\nFee: ${r.execution.fee}\nRisk: ${r.risk.reason_code}`:`REJECTED\nRisk: ${r.risk.reason_code}`;await refreshPaper();toast(r.accepted?'Paper execution ثبت شد':'Risk درخواست را رد کرد')}catch(err){out.className='result-box bad';out.textContent='REJECTED\n'+err.message;toast(err.message)}}
async function refreshPaper(){const [paper,events]=await Promise.all([api('/api/product/paper'),api('/api/product/paper/events?limit=100')]);state.paper=paper;state.events=events;renderPaper();renderEvents()}
function addMessage(kind,name,text,meta=''){const root=$('#aiTranscript'),el=document.createElement('div');el.className='message '+kind;el.innerHTML=`<b>${esc(name)}${meta?' · '+esc(meta):''}</b><p>${esc(text)}</p>`;root.appendChild(el);root.scrollTop=root.scrollHeight}
async function sendAI(e){e.preventDefault();const input=$('#aiMessage'),message=input.value.trim();if(!message)return;input.value='';addMessage('user','YOU',message);const turn='turn-'+(++state.turn)+'-'+crypto.randomUUID();try{const r=await api('/api/ai-room/message',{method:'POST',body:JSON.stringify({session_id:state.sessionId,conversation_id:state.conversationId,turn_id:turn,message})}),room=r.ai_room||r;addMessage('assistant','NEXUS AI ROOM',room.reply||'پاسخی ثبت نشد',`${room.intent||''} / ${room.decision?.status||''}`)}catch(err){addMessage('assistant','NEXUS GATE','درخواست fail-closed شد: '+err.message,'BLOCKED')}}
function bind(){$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#sidebarToggle').onclick=()=>document.body.classList.toggle('sidebar-collapsed');$('#reload').onclick=loadAll;$('#paperRefresh').onclick=refreshPaper;$('#paperOrder').onsubmit=submitPaper;$('#aiForm').onsubmit=sendAI;window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='b'){e.preventDefault();document.body.classList.toggle('sidebar-collapsed')}})}
window.addEventListener('DOMContentLoaded',()=>{bind();loadAll()});
})();