(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={overview:null,paper:null,events:null,strategies:null,mission:null,risk:null,recovery:null,notifications:null,registry:null,research:null,lastRisk:null,sessionId:'nexus-ui-'+crypto.randomUUID(),conversationId:'product-'+crypto.randomUUID(),turn:0};
const labels={overview:['NEXUS / MISSION CONTROL','مرکز فرمان NEXUS'],data:['NEXUS / DATA CORE','داده و بازار'],research:['NEXUS / RESEARCH / BACKTEST','بک‌تست و پژوهش'],paper:['NEXUS / PAPER EXECUTION','ترید دمو و Paper Execution'],risk:['NEXUS / PORTFOLIO / RISK','ریسک و پرتفوی'],ai:['NEXUS / AI ROOM','اتاق هوش مصنوعی'],strategies:['NEXUS / STRATEGY LAB','Strategy Factory'],agents:['NEXUS / AGENTS / QUEUE','عامل‌ها و صف'],audit:['NEXUS / AUDIT / RECOVERY','ممیزی و بازیابی'],live:['NEXUS / LIVE / LOCKED','ترید اصلی — قفل‌شده']};
function esc(v){return String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const res=await fetch(path,{cache:'no-store',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options});let payload;try{payload=await res.json()}catch{throw Error('پاسخ backend قابل خواندن نیست')}if(!res.ok)throw Error(payload.detail||payload.error||`HTTP ${res.status}`);return payload}
function setGateway(ok,msg){const p=$('#gatewayState');p.className='status '+(ok?'good':'bad');p.querySelector('b').textContent=msg}
function metric(label,value,detail=''){return`<div class="metric"><span>${esc(label)}</span><b>${esc(value)}</b><small>${esc(detail)}</small></div>`}
function bool(v){return v===true?'YES':v===false?'NO':'—'}
function pct(v){const n=Number(v);return Number.isFinite(n)?(n*100).toFixed(2)+'%':'—'}
function num(v,d=2){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('fa-IR',{maximumFractionDigits:d}):'—'}
function statusClass(v){return /available|active|complete|ready|pass|paper|verified|candidate|executed/i.test(String(v))?'good':/locked|unavailable|denied|failed|error|killed|rejected/i.test(String(v))?'bad':'neutral'}
function show(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+view)?.classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageCode').textContent=labels[view][0];$('#pageTitle').textContent=labels[view][1]}
function renderOverview(){const x=state.overview;if(!x)return;$('#productState').textContent=x.delivery||'canonical-python-sidecar';$('#paperState').textContent=x.paper?.active?'ACTIVE':'UNAVAILABLE';$('#liveState').textContent=(x.live?.status||'LOCKED').toUpperCase();const m=x.mission_control||{};$('#missionBadge').className='badge '+statusClass(m.status);$('#missionBadge').textContent=String(m.status||'unavailable').toUpperCase();const mission=m.mission||{},queue=m.queue||{},counts=queue.counts||{};$('#missionSummary').innerHTML=[metric('MISSION',mission.status||m.status||'unavailable',mission.mission_id||''),metric('READY',counts.ready??counts.READY??'—','queue'),metric('RUNNING',counts.running??counts.RUNNING??'—','queue'),metric('AGENTS',Array.isArray(m.agents)?m.agents.length:'—','registered')].join('');$('#capabilityMap').innerHTML=Object.entries(x.capabilities||{}).map(([k,v])=>`<div class="capability"><span>${esc(k.replaceAll('_',' ').toUpperCase())}</span><b class="${statusClass(v)}">${esc(v)}</b></div>`).join('')}
function renderPaper(){const p=state.paper;if(!p)return;const a=p.account||{};$('#paperMetrics').innerHTML=[metric('CASH',a.cash||'—',a.currency||'USDT'),metric('EQUITY',a.equity||'—','paper'),metric('REALIZED PNL',a.realized_pnl||'0','paper'),metric('UNREALIZED',a.unrealized_pnl||'0','paper'),metric('SESSION',a.session_open?'OPEN':'CLOSED','control'),metric('KILL SWITCH',a.kill_switch_enabled?'ON':'OFF','control'),metric('EVENTS',p.event_count??'—','hash chained'),metric('POSITIONS',(a.positions||[]).length,'open')].join('');const pos=a.positions||[];$('#positions').innerHTML=pos.length?`<table class="data-table"><thead><tr><th>نماد</th><th>جهت</th><th>مقدار</th><th>ورود</th><th>Stop</th><th>Target</th></tr></thead><tbody>${pos.map(r=>{const st=(a.stops||[]).find(x=>x.symbol===r.symbol),tg=(a.targets||[]).find(x=>x.symbol===r.symbol);return`<tr><td class="mono">${esc(r.symbol)}</td><td>${esc(r.side)}</td><td>${esc(r.quantity)}</td><td>${esc(r.entry_price)}</td><td>${esc(st?.price)}</td><td>${esc(tg?.price)}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty-state">پوزیشن بازی وجود ندارد.</div>'}
function renderEvents(){const events=state.events?.events||[];const html=events.slice().reverse().map(e=>`<div class="event-row"><code>#${esc(e.sequence)}</code><b>${esc(e.event_type)}</b><span>${esc(e.payload?.symbol||e.payload?.reason_code||e.payload?.boundary||e.payload?.currency||'')}</span><code>${esc((e.event_digest||'').slice(0,16))}…</code></div>`).join('')||'<div class="empty-state">رویدادی وجود ندارد.</div>';$('#paperEvents').innerHTML=html;$('#auditEvents').innerHTML=html;$('#auditDigest').textContent=(state.paper?.head_event_digest||'—').slice(0,20)+'…'}
function renderStrategies(){const s=state.strategies;if(!s)return;$('#strategyFamilies').innerHTML=(s.families||[]).map(x=>`<article class="strategy-card"><span>${esc(x.status)}</span><h3>${esc(x.id)}</h3><p>Promotion ceiling: ${esc(x.promotion_ceiling)} · Live: ${esc(bool(x.live_execution_allowed))}</p></article>`).join('');$('#qualificationPath').innerHTML=(s.qualification_path||[]).map(x=>`<div class="stage">${esc(x)}</div>`).join('')}
function renderMission(){const m=state.mission;if(!m||m.status==='unavailable'){$('#agentState').innerHTML=`<div class="empty-state">Mission Control runtime در این دستگاه report فعال ندارد؛ وضعیت ساختگی نمایش داده نمی‌شود.<br><small>${esc(m?.reason||'')}</small></div>`;return}const q=m.queue||{},agents=m.agents||[],providers=m.providers||{};$('#agentState').innerHTML=`<div class="metric-grid">${metric('MISSION',m.mission?.status||'unknown',m.mission?.mission_id||'')}${metric('QUEUE',JSON.stringify(q.counts||{}),'current projection')}${metric('AGENTS',Array.isArray(agents)?agents.length:'—','registered')}${metric('PROVIDERS',typeof providers==='object'?Object.keys(providers).length:'—','projection')}</div><pre class="json-view">${esc(JSON.stringify({agents,providers,runners:m.runners,circuits:m.circuits,local_node:m.local_node},null,2))}</pre>`}
function renderLive(){const x=state.overview?.live||{};$('#liveDetails').innerHTML=[['STATUS',x.status||'locked'],['AUTHORITY',bool(x.live_trading_authority)],['CREDENTIALS',bool(x.exchange_credentials_configured)],['ORDERS',bool(x.orders_allowed)],['WITHDRAWALS',bool(x.withdrawals_allowed)],['PRODUCTION',bool(x.production_promotion_allowed)]].map(([a,b])=>`<div class="lock-item"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}
function renderRegistry(){const r=state.registry;if(!r)return;const maps=r.mappings||[];$('#registrySummary').innerHTML=[metric('REGISTRY',r.registry_version||'—','validated'),metric('PRIMARY',r.authority?.primary||'Bybit','canonical'),metric('MAPPINGS',maps.length,'semantic contracts'),metric('PRIVATE KEY',bool(r.private_credentials_required),'public only')].join('');$('#registryTable').innerHTML=`<table class="data-table"><thead><tr><th>Canonical</th><th>Market</th><th>TF</th><th>Finality</th><th>Sources</th></tr></thead><tbody>${maps.map(m=>`<tr><td class="mono">${esc(m.canonical_symbol)}</td><td>${esc(m.market_category)}</td><td>${esc(m.timeframe)}</td><td>${esc(m.finality)}</td><td><div class="source-stack">${(m.sources||[]).map(s=>`<span class="source-chip ${esc(s.role)}">${esc(s.exchange)} · ${esc(s.role)} · ${esc(s.status)}</span>`).join('')}</div></td></tr>`).join('')}</tbody></table>`}
function renderRisk(){const r=state.risk;if(!r)return;const s=r.state||{},p=r.policy||{},a=r.account||{};$('#riskMetrics').innerHTML=[`<article class="panel"><span>EQUITY</span><b>${esc(a.equity||s.equity)}</b><small>USDT</small></article>`,`<article class="panel"><span>EXPOSURE</span><b>${esc(s.current_exposure||'0')}</b><small>notional</small></article>`,`<article class="panel"><span>DAILY PNL</span><b>${esc(s.daily_realized_pnl||'0')}</b><small>realized</small></article>`,`<article class="panel"><span>POSITION LIMIT</span><b>${esc(p.max_position_fraction||'—')}</b><small>equity fraction</small></article>`,`<article class="panel"><span>AGGREGATE LIMIT</span><b>${esc(p.max_aggregate_fraction||'—')}</b><small>equity fraction</small></article>`,`<article class="panel"><span>DAILY LOSS LIMIT</span><b>${esc(p.max_daily_loss_fraction||'—')}</b><small>fail closed</small></article>`,`<article class="panel"><span>DRAWDOWN LIMIT</span><b>${esc(p.max_drawdown_fraction||'—')}</b><small>fail closed</small></article>`,`<article class="panel"><span>KILL SWITCH</span><b>${s.kill_switch?'ON':'OFF'}</b><small>paper control</small></article>`].join('');$('#riskPolicy').textContent=JSON.stringify(p,null,2)}
function renderRecovery(){const r=state.recovery;if(!r)return;$('#recoveryBadge').className='badge '+statusClass(r.status);$('#recoveryBadge').textContent=String(r.status||'unknown').toUpperCase();const html=[metric('STATUS',r.status||'—','fail closed'),metric('EVENTS',r.event_count??'—','journal'),metric('SEQUENCE',r.last_sequence??'—','replayed'),metric('ATOMIC',bool(r.atomic_journal),'fsync + replace')].join('');$('#recoveryMetrics').innerHTML=html;$('#overviewRecovery').innerHTML=html}
function renderNotifications(){const rows=state.notifications?.notifications||[];const html=rows.map(n=>`<div class="compact-row"><code>${esc((n.occurred_at||'').slice(11,19))}</code><b>${esc(n.event_type)}</b><span>${esc(JSON.stringify(n.payload||{}))}</span></div>`).join('')||'<div class="empty-state">هشدار عملیاتی جدیدی ثبت نشده است.</div>';$('#notificationList').innerHTML=html;$('#overviewNotifications').innerHTML=html}
function researchMetricCards(r){const m=r?.backtest?.metrics||{},e=r?.evidence||{};return[metric('RETURN',pct(m.total_return),'base'),metric('MAX DD',pct(m.max_drawdown),'base'),metric('FILLS',m.fill_count??'—','next-bar-open'),metric('OOS',pct(e.oos_score),'stress holdout'),metric('STRESS',pct(e.robustness_score),'worst return'),metric('REGIME PASS',num((e.regime_pass_ratio||0)*100,1)+'%','ordered slices')].join('')}
function renderChart(points){const root=$('#equityChart');if(!points?.length){root.className='chart-empty';root.textContent='منحنی قابل نمایش نیست.';return}const w=1000,h=260,pad=18,eq=points.map(x=>Number(x.equity)),dd=points.map(x=>Number(x.drawdown));const emin=Math.min(...eq),emax=Math.max(...eq),er=Math.max(emax-emin,1e-9),dmin=Math.min(...dd,0),dr=Math.max(0-dmin,1e-9);const xy=(arr,kind)=>arr.map((v,i)=>{const x=pad+(w-2*pad)*(i/Math.max(arr.length-1,1));const y=kind==='eq'?pad+(h-2*pad)*(1-(v-emin)/er):pad+(h-2*pad)*(Math.abs(v)/dr);return`${x.toFixed(1)},${y.toFixed(1)}`}).join(' ');root.className='';root.innerHTML=`<svg class="equity-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="grid" x1="${pad}" y1="${h/2}" x2="${w-pad}" y2="${h/2}"/><polyline class="equity" points="${xy(eq,'eq')}"/><polyline class="drawdown" points="${xy(dd,'dd')}"/></svg><div class="chart-legend"><span><i></i> Equity ${esc(num(eq.at(-1),2))}</span><span><i class="dd"></i> Drawdown ${esc(pct(dd.at(-1)))}</span></div>`}
function renderResearch(){const r=state.research;if(!r||r.status==='no_research_run')return;const q=r.qualification||{};$('#qualificationBadge').className='badge '+statusClass(q.status);$('#qualificationBadge').textContent=String(q.status||'unknown').toUpperCase();$('#researchMetrics').innerHTML=researchMetricCards(r);$('#researchEvidence').textContent=JSON.stringify({dataset:r.dataset,config:r.strategy_config,cost_model:r.cost_model,kill_criteria:r.kill_criteria,evidence:r.evidence,qualification:q,pipeline_digest:r.pipeline_digest},null,2);renderChart(r.backtest?.equity_curve);const fills=r.backtest?.fills||[];$('#backtestFills').innerHTML=fills.length?`<table class="data-table"><thead><tr><th>زمان</th><th>Side</th><th>Fill</th><th>Notional</th><th>Fee</th><th>Reason</th></tr></thead><tbody>${fills.map(f=>`<tr><td class="mono">${esc(f.execution_time)}</td><td>${esc(f.side)}</td><td>${esc(num(f.fill_price,6))}</td><td>${esc(num(f.notional,2))}</td><td>${esc(num(f.fee,4))}</td><td>${esc(f.reason)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Fill ثبت نشده است.</div>';$('#researchRunState').className='result-box '+(q.status==='paper_candidate'?'good':'bad');$('#researchRunState').textContent=`${q.status||'unknown'}\nDataset: ${r.dataset?.source||'—'} ${r.dataset?.row_count||'—'} candles\nPipeline: ${r.pipeline_digest||'—'}\nNo profitability claim.`}
async function loadAll(){setGateway(false,'در حال اتصال');try{const [overview,paper,events,strategies,mission,risk,recovery,notifications,registry,research]=await Promise.all([api('/api/product/overview'),api('/api/product/paper'),api('/api/product/paper/events?limit=100'),api('/api/product/strategies'),api('/api/product/mission-control'),api('/api/product/risk'),api('/api/product/recovery'),api('/api/product/notifications?limit=40'),api('/api/product/data/registry'),api('/api/product/research/last')]);Object.assign(state,{overview,paper,events,strategies,mission,risk,recovery,notifications,registry,research});renderOverview();renderPaper();renderEvents();renderStrategies();renderMission();renderLive();renderRegistry();renderRisk();renderRecovery();renderNotifications();renderResearch();setGateway(true,'Python backend متصل')}catch(e){setGateway(false,'Backend unavailable');toast(e.message)}}
async function refreshPaper(){const [paper,events,risk,recovery,notifications]=await Promise.all([api('/api/product/paper'),api('/api/product/paper/events?limit=100'),api('/api/product/risk'),api('/api/product/recovery'),api('/api/product/notifications?limit=40')]);Object.assign(state,{paper,events,risk,recovery,notifications});renderPaper();renderEvents();renderRisk();renderRecovery();renderNotifications()}
async function submitPaper(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={};for(const [k,v] of f.entries())payload[k]=String(v).trim();const out=$('#orderResult');out.className='result-box muted';out.textContent='در حال ارزیابی Risk…';try{const r=await api('/api/product/paper/order',{method:'POST',body:JSON.stringify(payload)});state.lastRisk=r;$('#lastRisk').textContent=JSON.stringify(r,null,2);out.className='result-box '+(r.accepted?'good':'bad');out.textContent=r.accepted?`ACCEPTED\nFill: ${r.execution.fill_price}\nFee: ${r.execution.fee}\nRisk: ${r.risk.reason_code}`:`REJECTED\nRisk: ${r.risk.reason_code}`;await refreshPaper();toast(r.accepted?'Paper execution ثبت شد':'Risk درخواست را رد کرد')}catch(err){out.className='result-box bad';out.textContent='REJECTED\n'+err.message;toast(err.message)}}
async function runResearch(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={symbol:String(f.get('symbol')),timeframe:String(f.get('timeframe')),family:String(f.get('family')),limit:Number(f.get('limit'))};$('#researchRunState').className='result-box muted';$('#researchRunState').textContent='در حال دریافت کندل بسته و اجرای backtest / OOS / stress / regime…';try{const r=await api('/api/product/research/run',{method:'POST',body:JSON.stringify(payload)});state.research=r;renderResearch();toast('پژوهش canonical تکمیل شد')}catch(err){$('#researchRunState').className='result-box bad';$('#researchRunState').textContent='FAIL CLOSED\n'+err.message;toast(err.message)}}
async function autoPaper(){if(!state.research||state.research.status==='no_research_run'){toast('اول Research/Backtest را اجرا کن');show('research');return}try{const r=await api('/api/product/paper/auto',{method:'POST',body:'{}'});state.lastRisk=r;$('#lastRisk').textContent=JSON.stringify(r,null,2);await refreshPaper();toast(r.accepted?'Auto Paper اجرا شد':`Auto Paper: ${r.status}`)}catch(err){toast(err.message)}}
async function control(path,payload){try{await api(path,{method:'POST',body:JSON.stringify(payload)});await refreshPaper();toast('کنترل Paper ثبت شد')}catch(err){toast(err.message)}}
function addMessage(kind,name,text,meta=''){const root=$('#aiTranscript'),el=document.createElement('div');el.className='message '+kind;el.innerHTML=`<b>${esc(name)}${meta?' · '+esc(meta):''}</b><p>${esc(text)}</p>`;root.appendChild(el);root.scrollTop=root.scrollHeight}
async function sendAI(e){e.preventDefault();const input=$('#aiMessage'),message=input.value.trim();if(!message)return;input.value='';addMessage('user','YOU',message);const turn='turn-'+(++state.turn)+'-'+crypto.randomUUID();try{const r=await api('/api/ai-room/message',{method:'POST',body:JSON.stringify({session_id:state.sessionId,conversation_id:state.conversationId,turn_id:turn,message})}),room=r.ai_room||r;addMessage('assistant','NEXUS AI ROOM',room.reply||'پاسخی ثبت نشد',`${room.intent||''} / ${room.decision?.status||''}`)}catch(err){addMessage('assistant','NEXUS GATE','درخواست fail-closed شد: '+err.message,'BLOCKED')}}
function bind(){$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#sidebarToggle').onclick=()=>document.body.classList.toggle('sidebar-collapsed');$('#reload').onclick=loadAll;$('#registryRefresh').onclick=loadAll;$('#paperRefresh').onclick=refreshPaper;$('#paperOrder').onsubmit=submitPaper;$('#researchForm').onsubmit=runResearch;$('#autoPaper').onclick=autoPaper;$('#sessionOpen').onclick=()=>control('/api/product/session',{open:true});$('#sessionClose').onclick=()=>control('/api/product/session',{open:false});$('#killOn').onclick=()=>control('/api/product/kill-switch',{enabled:true,reason_code:'user_emergency_stop'});$('#killOff').onclick=()=>control('/api/product/kill-switch',{enabled:false,reason_code:'paper_resume'});$('#aiForm').onsubmit=sendAI;window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='b'){e.preventDefault();document.body.classList.toggle('sidebar-collapsed')}})}
window.addEventListener('DOMContentLoaded',()=>{bind();loadAll()});
})();